### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by rishoej** [andrepolischuk/react-rotation#14]
Awesome React component!

Is there a way to add autoplay on the rotation like the play() feature on https://github.com/andrepolischuk/circlr

**Comment by andrepolischuk** [comment]
Good idea. Thanks. I think add `autoplay: Boolean` property for example. I will try add it on weekend. Or you can send PR.

**Comment by andrepolischuk** [comment]
@rishoej published as v1.2.0

**Comment by rishoej** [comment]
@andrepolischuk Thank you! :D
