### ISSUE TITLE
autoplay speed, pauseOnHover (autoplay related APIs)

### ISSUE THREAD

**Issue by cyberhck** [andrepolischuk/react-rotation#16]
need a little more APIs is there a plan to do that? or is PR welcome?

**Comment by andrepolischuk** [comment]
Good ideas, thanks. You can send me pr. I think we can pass autoplay speed to `props.autoPlay`. Component will use default speed if `props.autoPlay = true`, or custom if `props.autoPlay` is number.

**Comment by andrepolischuk** [comment]
Published as v1.3.0
