### ISSUE TITLE
Manually choose which image

### ISSUE THREAD

**Issue by GainorB** [andrepolischuk/react-rotation#18]
I want to use your component with a HTML5 Range Slider, but the slider can't interact with your component because there is no prop that is exposed to set the current rotated image.

**Comment by GainorB** [comment]
nvm did it myself :)

**Comment by lyleunderwood** [comment]
Hey @GainorB, I'm curious what your approach was here. Did you end up forking `react-rotation`, or did you find a simpler solution?
